# Generated by Django 5.1.3 on 2025-11-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tradeaccounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeaccounts',
            name='account_password',
            field=models.TextField(default='0000'),
        ),
        migrations.AlterField(
            model_name='tradeaccounts',
            name='account_name',
            field=models.CharField(),
        ),
    ]
