# Generated by Django 5.1.3 on 2025-11-29 15:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tradeaccounts_account_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeaccounts',
            name='expiration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tradeaccounts',
            name='subscription',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
